name: "toml editor 2"
description: "This is an updated version of ciiiii/toml-editor"
author: "ciii/sandstromviktor"
branding:
  icon: "file"
  color: "blue"
inputs:
  file:
    description: "The relative path of toml file"
    required: true
  key:
    description: "Key need to modify"
    required: true
  value:
    description: "Value to set"
    required: true

runs:
  using: "docker"
  image: "Dockerfile"
